name: 'Bugsnag Report Build'
description: 'Github Action that will report a new build to Bugsnag'
author: 'Luke Hansford <@lhansford>'
inputs:
  apiKey:
    description: 'Your Bugsnag API Key'
    required: true
  appVersion:
    description: 'A version string for the build to report. If not set it will default to the version in package.json. This will only work if actions/checkout@v2 is used first.'
    required: false
  builderName:
    description: 'The name of the person/machine that trigerred this build.'
    required: false
  failCiIfError:
    description: 'If true then CI will fail if this action fails.'
    required: false
    default: false
  releaseStage:
    description: 'The release stage of the build. The default is `production`.'
    default: 'production'
    required: false
  sourceControlProvider:
    description: 'The source control provider. The default is `github`.'
    default: 'github'
    required: false
  sourceControlRepository:
    description: 'The source control repository. The default is the repository running the Github Action.'
    required: false
  sourceControlRevision:
    description: 'The source control revision. The default is the SHA for the running Github Action.'
    required: false
branding:
  color: 'blue'
  icon: 'upload'
runs:
  using: 'node12'
  main: 'dist/index.js'
