on: [push]

jobs:
  bugsnagReportBuild:
    runs-on: ubuntu-latest
    name: Bugsnag - Report Build
    steps:
    - uses: actions/checkout@v3

    - name: report
      uses: lhansford/bugsnag-report-build-action@main
      with:
        apiKey: ${{ secrets.bugsnag_api_key }}
        builderName: 'Luke Hansford'
        failCiIfError: true

  pingBugsnag:
    runs-on: ubuntu-latest
    name: Bugsnag - Ping
    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: npm install

    - name: Ping Bugsnag
      run: npm run ping-bugsnag
